/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*http://weather.yahooapis.com/forecastrss?w=2502265&u=c*/
  
/*
Get value from Bootstrap dropdown menu
*/



$('#dropdown li').on('click', function(){
    alert($(this).text());
  $(function () {  
  var weather,  
    rss = 'http://weather.yahooapis.com/forecastrss?w=2306180&u=c',  
    url = 'https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?&q=' + encodeURIComponent(rss);  
  $.ajax({  
    type: "GET",  
    url: url,  
    dataType: "json",  
    error: function (e) {  
      console.log('oh no');  
    },  
    success: function (e) {  
      var weather = $(e);  
      console.log(weather);  
    }  
  });  
;  
  });  
 
  
  

   /* 2306179*/




});
